import streamlit as st
import sqlite3
import config
from src.ui.styles import inject_mac_styles
from src.ui.components import bento_card, render_agent_bar
from src.utils import llm

# Inject styles at page level for multi-page support
inject_mac_styles()

st.title("Morning Brief")
st.markdown("<p class='mac-subtext'>Your daily strategic synthesis. Generated by the Firehouse at 7:00 AM.</p>", unsafe_allow_html=True)

# 1. TOP LEADS BENTO
st.subheader("Priority Targets")
try:
    conn = sqlite3.connect(str(config.DB_PATH))
    conn.row_factory = sqlite3.Row
    # Fetch top 3 HIGH equity prospects
    prospects = conn.execute("""
        SELECT owner_name, address, parcel_number, hold_years 
        FROM prospects 
        WHERE equity_score = 'HIGH' 
        ORDER BY created_at DESC LIMIT 3
    """).fetchall()
    conn.close()

    if prospects:
        cols = st.columns(3)
        for i, p in enumerate(prospects):
            with cols[i]:
                bento_card(
                    title=p['address'],
                    content=f"Owner: {p['owner_name']}",
                    subtext=f"Hold: {p['hold_years']} yrs | APN: {p['parcel_number']}"
                )
    else:
        st.info("No high-priority leads identified in the last sweep.")
except Exception as e:
    st.error(f"Error loading leads: {e}")

# 2. MANAGER'S THOUGHT OF THE DAY
st.subheader("The Principal's Counsel")
try:
    # Use the elite reasoning model to pull wisdom
    thought_prompt = "Provide one sentence of high-level strategic wisdom for a commercial real estate principal based on the Greg Pinneo 'Transaction Engineering' doctrine. Be pithy and authoritative."
    thought = llm.complete(thought_prompt, agent="manager")
    
    st.markdown(f"""
    <div class="bento-card" style="border-left: 4px solid var(--mac-accent);">
        <p style="font-style: italic; font-size: 18px; line-height: 1.6;">"{thought}"</p>
        <span class="mac-subtext">— The Third Partner</span>
    </div>
    """, unsafe_allow_html=True)
except Exception as e:
    st.info("Manager is contemplating today's strategy...")

# 3. RECENT INTEL (Audit Trail)
st.subheader("Recent Intelligence")
brief_path = config.DATA_DIR / "morning_brief.md"
if brief_path.exists():
    with open(brief_path, "r", encoding="utf-8") as f:
        content = f.read()
    st.markdown(f"<div class='bento-card'>{content}</div>", unsafe_allow_html=True)
else:
    st.info("Comprehensive brief is being compiled by the Firehouse.")

# 4. AGENT STATUS BAR (Fixed at bottom)
render_agent_bar()
