import streamlit as st
from pathlib import Path
import config

st.title("Morning Brief")
st.markdown("Your daily synthesis. Generated by the Firehouse at 7:00 AM.")

brief_path = config.DATA_DIR / "morning_brief.md"

if brief_path.exists():
    with open(brief_path, "r", encoding="utf-8") as f:
        content = f.read()
    st.markdown(content)
else:
    st.info("The Morning Brief has not been generated yet. It will run at 7:00 AM, or you can manually trigger it from the command line.")
